docs:
  input: raw_docs
  op: docs

pdoc:
  project: ura
  op: docs

md_vars:
  global:
    project_name: ura
    repo_name: urasunday
    site: ura.hyaku.download
    organization: hyaku-dl
    user: whinee
    codacy_id: 385ceb2d55424256a93f9ad6f8007f91
    dc_acc: whi_ne | whinyaan.xyz#5135
    dc_link: https://discord.com/users/867696753434951732
    dc_inv: JbAtUxGcJZ
    mail_acc: whinyaan@pm.me
    mail_link: mailto:whinyaan@pm.me

  local:
    README:
      title: ura
      desc: ""

rules:
  del:
  repl:
    'src="https://${site}/assets':
      - 'src="./assets'
    "src='https://${site}/assets":
      - "src='./assets"
    "](https://${site}/assets":
      - "](./assets"

requirements:
  dev: dev_req.txt
  prod: requirements.txt

env:
  dev:
    req:
      - prod
      - dev

license:
  year: 2022
  type: MIT
  cholder:
    whinee:
      hyaku-dl:
        hyaku:
          year: 2022
          platform: Github
      MangDL:
        MangDL:
          year: 2021-2022
          platform: Github
      Pirate-Kings:
        YAMHL:
          year: 2022
          platform: Github