docs:
  input: raw_docs
  op: docs

pdoc:
  project: ura
  op: docs

mako:
  gen:
    path:
      - changelog.mako
    glob:
      - docs/**/**/index.mako

md_vars:
  global:
    project_name: ura
    repo_name: urasunday
    site: ura.hyaku.download
    scripts_url: ura.hyaku.download/scripts
    organization: hyaku-dl
    user: whinee
    year: 2022
    codacy_id: 385ceb2d55424256a93f9ad6f8007f91
    dc_acc: whi_ne | whinyaan.xyz#5135
    dc_link: https://discord.com/users/867696753434951732
    dc_inv: JbAtUxGcJZ
    mail_acc: whinyaan@pm.me
    mail_link: mailto:whinyaan@pm.me
    desc: |-
      A Basic Urasunday Scraper
    long_desc: |-
      A no-nonsense, simple and easy to use scraper for urasunday.com
    long_desc_md: |-
      A no-nonsense, simple and easy to use scraper for <a target="_blank" href="https://urasunday.com">urasunday</a>

  local:
    README:
      title: ura

rules:
  del:
  repl:
    'src="https://${site}/assets':
      - 'src="./assets'
    "src='https://${site}/assets":
      - "src='./assets"
    "](https://${site}/assets":
      - "](./assets"

requirements:
  dev: dev_req.txt
  prod: requirements.txt

env:
  dev:
    req:
      - prod
      - dev

license:
  year: 2022
  type: MIT
  cholder:
    whi_ne:
      user: whinee
      projects:
        hyaku-dl:
          hyaku:
            year: 2022
            platform: Github
        MangDL:
          MangDL:
            year: 2021-2022
            platform: Github
        Pirate-Kings:
          YAMHL:
            year: 2022
            platform: Github

fetch:
  project_name: urasunday
  system: |-
    PF_INFO="os host kernel uptime pkgs memory" PF_COL1=69 PF_COL2=70 PF_SEP=": " pfetch
  project: |-
    onefetch --no-palette --no-bots -d languages lines_of_code size --show-logo never -a emacs-lisp
  types:
    Project Source: |-
      onefetch --no-palette --no-bots --show-logo never -e *.sh *.py scripts/ site/ -d git_info project head pending version created dependencies authors last_change contributors repo commits size license
    Core: |-
      onefetch --no-palette --no-bots --show-logo never -e *.sh *.py scripts/ site/ ura/gui -d git_info project head pending version created dependencies authors last_change contributors repo commits size license
    GUI: |-
      onefetch --no-palette --no-bots --show-logo never -e *.sh *.py scripts/ site/ ura/src ura/gui.py -d git_info project head pending version created dependencies authors last_change contributors repo commits size license
    Documentation: |-
      onefetch --no-palette --no-bots --show-logo never -e ura/ -T markup prose -d git_info project head pending version created dependencies authors last_change contributors repo commits size license