#! /bin/sh
curl -L -o ura.AppImage https://github.com/hyaku-dl/urasunday/releases/download/0.0.0.0-alpha.3/ura-linux-x86_64.AppImage
chmod +x ./ura.AppImage
./ura.AppImage --appimage-extract
rm -rf ./ura.AppImage
rm -rf /usr/share/ura
mv squashfs-root /usr/share/ura
echo '#! /bin/sh
"exec" "/usr/share/ura/usr/bin/python3.10" "$0" "$@"
# -*- coding: utf-8 -*-
import re
import sys
from ura.cli import cli
if __name__ == "__main__":
  sys.argv[0] = re.sub("r(-script\.pyw|\.exe)?$", "", sys.argv[0])
  sys.exit(cli())' > /usr/bin/ura
chmod +x /usr/bin/ura
rm -rf linux-install.sh