<!-- markdownlint-disable MD024 MD025 -->

<!--

Added
    For adding new features.
    - user
    - dev
    - minor
Changed
    For changes in existing functionality.
    - user
    - dev
Deprecated
    For marking features as `deprecated`.
    - patch
Removed
    For removing features.
    - user
    - dev
Fixed
    For any kind of fixes, formatting not included.
Security
    For any attempts to fix a security vulnerability.

-->

# 0 0 0 0 0 5

## Added

- Loading screen for app initialization

## Fixed

- AppImages to be marked as AppImages (means that the config now goes on the config folder instead of the same directory as the AppImage)

# 0 0 0 0 0 4

## Added

- Initialization of configuration file

# 0 0 0 0 0 3

## Fixed

- `vls` string on `ura/__init__.py` to `[0, 0, 0, 0, 0, 3]`

# 0 0 0 0 0 2

## Fixed

- Unquoted `__version__` string on `ura/__init__.py`

# 0 0 0 0 0 1

## Removed

- Useless imports

# 0 0 0 0 0 0

Initial release of the application
