<!-- markdownlint-disable MD024 MD025 -->

<!--

- `Added` for new features.
    - user
    - dev
    - minor
- `Changed` for changes in existing functionality.
    - user
    - dev
- `Deprecated` for soon-to-be removed features.
    - patch
- `Removed` for now removed features.
    - user
    - dev
- `Fixed` for any bug fixes.
- `Security` in case of vulnerabilities.

-->

# 0 0 0 0 0 5

## Added

- Loading screen for app initialization

## Fixed

- AppImages to be marked as AppImages

# 0 0 0 0 0 4

## Added

- Initialization of configuration file

# 0 0 0 0 0 3

## Fixed

- `vls` string on `ura/__init__.py` to `[0, 0, 0, 0, 0, 3]`

# 0 0 0 0 0 2

## Fixed

- Unquoted `__version__` string on `ura/__init__.py`

# 0 0 0 0 0 1

## Removed

- Useless imports

# 0 0 0 0 0 0

Initial release of the application
