---
title: Latest Commit
---

## **Summary**

Massive documentation overhaul!

## **Changes**

<!--

Added
    For adding new features.
    - user
    - dev
    - minor
Changed
    For changes in existing functionality.
    - user
    - dev
Deprecated
    For marking features as `deprecated`.
    - patch
Removed
    For removing features.
    - user
    - dev
Fixed
    For any kind of fixes, formatting not included.
Security
    For any attempts to fix a security vulnerability.

-->

### **Added**

<!--
For adding new features.
    - user
    - dev
    - minor
-->

### **Changed**

<!--
For changes in existing functionality.
    - user
    - dev
-->

- `dev/scripts/py/main.py`'s `main` function to also generate scripts.

### **Deprecated**

<!--
For marking features as `deprecated`.
    - patch
-->

### **Removed**

<!--
For removing features.
    - user
    - dev
-->

### **Fixed**

<!--
For any kind of fixes, formatting not included.
-->

- `dev/raw_docs/changelog.mako` as it cannot parse the version bump's description if it contained a hash (`#`) character.
- `dev/raw_docs/changelog.mako`'s incorrect latest version bump.
- `dev/scripts/py/rn_md.py` to read the correct markdown file for the latest release's notes.

### **Security**

<!--
For any attempts to fix a security vulnerability.
-->