---
title: Latest Commit
---

## **Summary**

Just read the thingy below...

## **Changes**

<!--

Added
    For adding new features.
    - user
    - dev
    - minor
Changed
    For changes in existing functionality.
    - user
    - dev
Deprecated
    For marking features as `deprecated`.
    - patch
Removed
    For removing features.
    - user
    - dev
Fixed
    For any kind of fixes, formatting not included.
Security
    For any attempts to fix a security vulnerability.

-->

### **Added**

<!--
For adding new features.
    - user
    - dev
    - minor
-->

- Added multiple terms to `dev/constants/dictionary.txt`. Honestly tho, shouldn't be recorded anymore, given how much I modify it.
- A

### **Changed**

<!--
For changes in existing functionality.
    - user
    - dev
-->

- Improved sourced shell script
- Made all headings in `dev/raw_docs/changelog.mako` bold
- Modified `cc` function in `dev/scripts/py/main.py`
- Modified `push` function in `dev/scripts/py/main.py` to run `cc` function
- Modified `main` function in `dev/scripts/py/main.py` to be able to receive argument

### **Deprecated**

<!--
For marking features as `deprecated`.
    - patch
-->

### **Removed**

<!--
For removing features.
    - user
    - dev
-->

- `PYTHON_DIR` in `dev/scripts/ps1/start.ps1`

### **Fixed**

<!--
For any kind of fixes, formatting not included.
-->

- `.github/workflows/build.yml`'s backlash issues

### **Security**

<!--
For any attempts to fix a security vulnerability.
-->