---
title: Latest Commit
---

## **Summary**

This commit aims to improve the developer utilities, and bring it back to its working state.

The documentation are also being improved.

## **Changes**

<!--

Added
    For adding new features.
    - user
    - dev
    - minor
Changed
    For changes in existing functionality.
    - user
    - dev
Deprecated
    For marking features as `deprecated`.
    - patch
Removed
    For removing features.
    - user
    - dev
Fixed
    For any kind of fixes, formatting not included.
Security
    For any attempts to fix a security vulnerability.

-->

### **Added**

<!--
For adding new features.
    - user
    - dev
    - minor
-->

- Comment in the latest commit for version bumps and comments on the latest commit (this one!)
- pdoc .mako templates
- Documentation of header styles
- Support for installable modules for developer utilities (`dev/scripts/py/inst_mods/*`)

### **Changed**

<!--
For changes in existing functionality.
    - user
    - dev
-->

- Formatted `.md` and `.py` files

### **Deprecated**

<!--
For marking features as `deprecated`.
    - patch
-->

### **Removed**

<!--
For removing features.
    - user
    - dev
-->

### **Fixed**

<!--
For any kind of fixes, formatting not included.
-->

### **Security**

<!--
For any attempts to fix a security vulnerability.
-->