---
title: Latest Commit
---

## **Summary**

This commit aims to improve the developer utilities, and bring it back to its working state.

The documentation are also being improved.

## **Changes**

<!--

Added
    For adding new features.
    - user
    - dev
    - minor
Changed
    For changes in existing functionality.
    - user
    - dev
Deprecated
    For marking features as `deprecated`.
    - patch
Removed
    For removing features.
    - user
    - dev
Fixed
    For any kind of fixes, formatting not included.
Security
    For any attempts to fix a security vulnerability.

-->

### **Added**

<!--
For adding new features.
    - user
    - dev
    - minor
-->

- Added SC2045 exclusion for `dev/scripts/sh/source.sh` cuz' shellcheck do be like that.
- Added multiple entries to `dev/constants/dictionary.txt`, cuz' spell checking.
- Added Wakatime badge and beta testing notice on `docs/README.md`.

### **Changed**

<!--
For changes in existing functionality.
    - user
    - dev
-->

- Refactored `dev/scripts/py/main.py` as `Jedi` is a fucking bitch, and whines about my match statements
- Refactored the app for easier maintenance in anticipation of the maintenance phase of the app

### **Deprecated**

<!--
For marking features as `deprecated`.
    - patch
-->

### **Removed**

<!--
For removing features.
    - user
    - dev
-->

### **Fixed**

<!--
For any kind of fixes, formatting not included.
-->

- Codacy link on `docs/README.md` to link to the proper branch of the repository

### **Security**

<!--
For any attempts to fix a security vulnerability.
-->