---
title: Latest Commit
---

## **Summary**

<!-- cspell: disable-next-line -->
Just read the thingy below...

## **Changes**

<!--

Added
    For adding new features.
Changed
    For changes in existing functionality.
Deprecated
    For marking features as `deprecated`.
Removed
    For removing features.
Fixed
    For any kind of fixes, formatting not included.
Security
    For any attempts to fix a security vulnerability.

-->

### **Added**

<!--
For adding new features.
-->

### **Changed**

<!--
For changes in existing functionality.
-->

- Changed `dev/scripts/py/main.py`'s `push` function corresponding subcommand to be `push`, cuz' muscle memory.

### **Deprecated**

<!--
For marking features as `deprecated`.
-->

### **Removed**

<!--
For removing features.
-->

### **Fixed**

<!--
For any kind of fixes, formatting not included.
-->

### **Security**

<!--
For any attempts to fix a security vulnerability.
-->